[package]
name = "peroxide"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4"] }
sha2 = "0.10"
goblin = "0.6"
chrono = "0.4"
